### PR TITLE
fixing minor typos

### PR DESCRIPTION
**Pull request by GuilhermeCamposo**
fixing two minor typos in the guides

### CODE REVIEW

**Comment by danieloh30** [comment]
Thanks for the PR! Can you leave "Select" for now? I've received interesting feedback several times like "click" is an old term for people who used to use a mouse device but recently they don't use it anymore, especially, younger gen don't even know it. Instead "select" might be better for them to understand. I probably will replace "click" with "select" eventually.

**Comment by GuilhermeCamposo** [comment]
I did the change to be consistent with other occurrences. If we are not changing this, I think is easier to drop this PR and manually fix the other typo.

**Comment by danieloh30** [comment]
This is still an experimental thing. For example, you can find a bunch of "select" terms here" https://github.com/rh-mad-workshop/mad-dev-guides-m1/blob/main/documentation/modules/ROOT/pages/3-analyze.adoc
If you feel more comfortable creating a new one only for the typo rather than updating this PR, let me know.

**Comment by GuilhermeCamposo** [comment]
There is another PR just for that https://github.com/rh-mad-workshop/mad-dev-guides-m1/pull/2. I'm closing this one

**Pull request closed without merging**
